
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author derek
 */
public class client extends javax.swing.JFrame {

    /**
     * Creates new form client
     */
    public client() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResults_text = new javax.swing.JTextArea();
        searchString = new javax.swing.JTextField();
        b_searchName = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b_searchID = new javax.swing.JButton();
        r_podcast = new javax.swing.JRadioButton();
        r_musicVideo = new javax.swing.JRadioButton();
        r_album = new javax.swing.JRadioButton();
        r_movie = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchResults_text.setColumns(20);
        searchResults_text.setRows(5);
        jScrollPane1.setViewportView(searchResults_text);

        searchString.setName(""); // NOI18N
        searchString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStringActionPerformed(evt);
            }
        });

        b_searchName.setText("Search Name");
        b_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iTunesSearchAction(evt);
            }
        });

        jLabel1.setText("Search ");

        b_searchID.setText("Search ID");
        b_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iTunesSearchAction(evt);
            }
        });

        buttonGroup.add(r_podcast);
        r_podcast.setText("podcast");

        buttonGroup.add(r_musicVideo);
        r_musicVideo.setText("musicVideo");

        buttonGroup.add(r_album);
        r_album.setText("album");

        buttonGroup.add(r_movie);
        r_movie.setText("movie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchString, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_musicVideo)
                        .addGap(18, 18, 18)
                        .addComponent(r_movie)
                        .addGap(48, 48, 48)
                        .addComponent(b_searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_podcast)
                        .addGap(18, 18, 18)
                        .addComponent(r_album)
                        .addGap(70, 70, 70)
                        .addComponent(b_searchID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_podcast)
                    .addComponent(r_album)
                    .addComponent(b_searchID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_musicVideo)
                    .addComponent(r_movie)
                    .addComponent(b_searchName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    
    private void b_iTunesSearchAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iTunesSearchAction
        // TODO add your handling code here:
        
           String search =  searchString.getText();
    
    String SearchString = search.replaceAll("\\s+", "+");
    StringBuilder urlBuilder = new StringBuilder();
    StringBuilder stringBuilder = new StringBuilder();
    String stringURL = "http://localhost:8080/itunesRestClient/webresources/itunes/artist/";
    urlBuilder.append(stringURL);
    Object src = evt.getSource();
  
    if(src == b_searchName){   
        urlBuilder.append("name/").append(SearchString);    
    }
    else{      
      urlBuilder.append(SearchString);         
    }
    
    if(r_podcast.isSelected()){
        urlBuilder.append("/podcast");
    }
    if(r_album.isSelected()){
        urlBuilder.append("/album"); 
    } 
    if(r_musicVideo.isSelected()){
        urlBuilder.append("/musicVideo");
    }
    if(r_movie.isSelected()){  
        urlBuilder.append("/movie");    
    }
    
     try{
            URL url = new URL(urlBuilder.toString());
            HttpURLConnection conn; 
            conn = (HttpURLConnection) url.openConnection();   
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accecpt", "application/vnd.github.v3+json");           
            InputStream inputStream = conn.getInputStream();
            InputStreamReader isr = new InputStreamReader(inputStream);      
            BufferedReader bufferedReader = new BufferedReader(isr);
            for (String line ; (line = bufferedReader.readLine()) != null; ) {
                stringBuilder.append(line);
            }         
            searchResults_text.setText(stringBuilder.toString()); 
  
        }catch(IOException e){
            System.out.println(e.toString());
            
        }
        
    }//GEN-LAST:event_b_iTunesSearchAction

    private void searchStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_searchID;
    private javax.swing.JButton b_searchName;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r_album;
    private javax.swing.JRadioButton r_movie;
    private javax.swing.JRadioButton r_musicVideo;
    private javax.swing.JRadioButton r_podcast;
    private javax.swing.JTextArea searchResults_text;
    private javax.swing.JTextField searchString;
    // End of variables declaration//GEN-END:variables
}
